{
 "title": "hospital beds",
 "time": { "from": "2026-05-14T19:31:30.000Z", "to": "2026-05-14T19:32:20.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bed_id",
    "label": "Select Bed",
    "query": "SELECT DISTINCT bed_id FROM hospital.vitals_raw"
   }
  ]
 },
 "panels": [
  {
   "title": "5-Minute Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    window_start::timestamp AS time,\r\n    avg_heart_rate\r\nFROM hospital.vitals_agg\r\nWHERE bed_id = '$bed_id'\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "heart rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    recorded_at::timestamp AS time,\r\n    heart_rate\r\nFROM hospital.vitals_raw\r\nWHERE bed_id = '$bed_id'\r\nORDER BY time ASC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Vital Signs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    heart_rate \r\nFROM hospital.vitals_raw \r\nWHERE bed_id = '$bed_id' \r\nORDER BY recorded_at DESC \r\nLIMIT 1"
    }
   ]
  }
 ]
}