{
 "title": "pipeline monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "how many hospital vital records are being processed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_numRecordsOutPerSecond[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "description": "monitoring jvm heap since flink uses it",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime & Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flink_jobmanager_job_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "gauge",
   "description": "shows if Flink is falling behind the Kafka producer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}